### ISSUE TITLE
Alignment Dialog RUN APIリクエスト処理組み込み

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/MRIAnalysisStudioforMouse#79]
Alignment Dialog からの RUN API へのリクエスト処理を組み込む

#### 対応内容

- node type は、AlignmentNode とする（FE/BE）
  - **[確認]** AlignmentNode は、Inputの Node と Algorithm の Node の中間の位置づけとなるが、BackEnd側でスムーズに組み込みは可能であるか？
    - BE では、AlignmentNode のparam の内容をもとに、画像の加工処理が行われる。
    - もしスムーズな組み込みが難しければ、 AlignmentNode は、InputとAlgorithmに分離することも想定。
  - 組み込み可能であれば、BE に、AlignmentNode の処理モックモジュール（中身は空）を用意しておく。

- param には以下を設定（FE/BE）
  ```yaml
  alignments:
    # Repeat the following for the number of images.
    - 
      image_id: 0
      x_pos: 0
      y_pos: 0
      z_pos: 0
      x_rotate: 0.0
      y_rotate: 0.0
      z_rotate: 0.0
      x_resize: 0.0
      y_resize: 0.0
      z_resize: 0.0
  ```

- Alignment の画像リストが1件以上の場合、RUNを実行可能（FE）
  - → 0件の場合は、「please select input file」（現行システムでも表示されるエラー）を表示

- 関連
  - #56 

- 希望期日
  - 5/15

**Comment by Reactplus-Hao** [comment]
Tích hợp phần xử lý request từ Alignment Dialog đến RUN API

- Nội dung xử lý
node type sẽ là AlignmentNode （FE/BE）

   - [KH confirm] AlignmentNode là vị trí nối giữa Node Input và Node Algorithm, vậy thì ở phía BE có thể xử lý tích hợp mượt mà được không?
      - Ở phía BE sẽ dựa vào nội dung param của AlignmentNode và tiến hành xử lý chỉnh sửa ảnh
      - Nếu như việc xử lý tích hợp không mượt mà, thì cũng có thể phân tách AlignmentNode thành Input và Algorith
   - Nếu có thể xử lý, thì nhờ bên BE chuẩn bị sẵn mock module xử lý của AlignmentNode（Để body trống)
 
- Set thông số sau cho param (FE/BE）

```
alignments:
  # Repeat the following for the number of images.
  - 
    image_id: 0
    x_pos: 0
    y_pos: 0
    z_pos: 0
    x_rotate: 0.0
    y_rotate: 0.0
    z_rotate: 0.0
    x_resize: 0.0
    y_resize: 0.0
    z_resize: 0.0
```
- Trường hợp list ảnh Alignment có từ 1 ảnh trở lên, thì mới có thể thực hiện RUN（FE）
    - → Trường hợp list ảnh là 0, thì hãy hiển thị lỗi 「please select input file」（Lỗi được hiển thị trên hệ thống hiện tại
- Ticket liên quan:
   - https://github.com/arayabrain/MRIAnalysisStudioforMouse/issues/56
- Deadline: 5/15
